### ISSUE TITLE
502 Gateway timeout, "Health Checks failed" for container from mikethecanuck/infrastructure-improvements

### ISSUE THREAD

**Issue by MikeTheCanuck** [hackoregon/housing-backend#13]
I thought for sure I had the container/Travis/deploy configured correctly for the Housing backend last night.  Nope.

The container builds and runs perfectly in the local setting - either running `start-proj.sh` or building an old-fashioned container with `docker build` and running it with `docker start`.

It appears from our investigations that the app startup time, in a Docker/AWS environment, is too slow to respond to Health Check requests in time to be considered a healthy container.

Health Check requests in this context are a simple "GET /" request to the application, where gunicorn is the web server we're using to host the Django application.

The same Health Check works fine for the same gunicorn/Docker/AWS deployment for all Budget, Homelessness and Emergency Response.  [Transportation has other application problems that prevent us from getting that container to run at all at this time, so we can't make the comparison.]

**Comment by troypdx** [comment]
I think we solved this with the addition of coroutine multi-tasking components (gevent.monkey) to WSGI.
