### ISSUE TITLE
Rent endpoint is not returning valid report years

### ISSUE THREAD

**Issue by troypdx** [hackoregon/housing-backend#17]
The current deployment (from the jaym-apr15 branch) at: http://hacko-integration-658279555.us-west-2.elb.amazonaws.com/housing/#!/rent/rent_list

We're still investigating but wanted to give front-end folks a heads up.

**Comment by jaymcgrath** [comment]
This was fixed by 50d0a17396e77d03b67bb50634e2539339b268f7
