### ISSUE TITLE
Add neighborhood ids to API responses

### ISSUE THREAD

**Issue by nmuldavin** [hackoregon/housing-backend#23]
To associate data from various places without fear of typos, the frontend needs to have neighborhood ids as defined [here](https://github.com/hackoregon/housing-backend/blob/datasources/NeighborhoodProfiles.csv) sent over with API responses. I figure this should be straightforward?

**Comment by troypdx** [comment]
Hi Noah - So everyone is clear we want:

GET /housing/affordable/37/
to return:
```
{
  "affordable": true,
  "demographic": "Latino",
  "housing_size": "1-BR",
  "NP_ID": "3",
  "neighborhood": "Centennial-Glenfair-Wilkes"
}
```

**Comment by troypdx** [comment]
And GET http://service.civicpdx.org/housing/rent/?rent_amt_gt=473&rent_amt_lt=475
to return:
```
[
  {
    "year": 2016,
    "rent_amt": 474,
    "housing_size": "Studio",
    "nh_id": "6",
    "neighborhood": "Gateway"
  }
]
```

**Comment by nmuldavin** [comment]
perfect!

**Comment by jaymcgrath** [comment]
To clarify, NP_ID and nh_id are the same value, right? Is there a reason why they have different names here?  They will be pulled from the same table, but I can name them differently in the API serializer if that's what works best

**Comment by nmuldavin** [comment]
They are the same as far as I know, I figured there was some backend-ey reason why they were named different in the above samples. I was probably going to normalize them to both say 'id' on the front end anyways

**Comment by jaymcgrath** [comment]
OK, i think it was just awkward naming. I can standardize them in my next PR

**Comment by gabrielesh** [comment]
I believe this was done by @jaymcgrath so I'm marking this closed
