### ISSUE TITLE
Should we rename the repo to "housing-backend"? 

### ISSUE THREAD

**Issue by troypdx** [hackoregon/housing-backend#40]

**Comment by JohnTasto** [comment]
I vote yes. If Hack Oregon intends to continue working on this next year, we should remove the date from the name.

It would only be a minor inconvenience to anyone who has already cloned it:
http://zanshin.net/2012/04/03/renaming-github-repository/

**Comment by ericalmadovapsu** [comment]
I also agreed. I think the change will make more sense than the current name in the long run. 

This change will also effect the loader slightly. We will need to change the urls for where the files are pulled from.
