### ISSUE TITLE
Add CORS support

### ISSUE THREAD

**Issue by DingoEatingFuzz** [hackoregon/housing-backend#64]
When developing locally, the frontend is on port 3000 and the backend is on port 8000. Without the access-control-allow-origin header set, this doesn't fly.

![image](https://cloud.githubusercontent.com/assets/174740/23445491/ad76bf36-fdf0-11e6-9eb0-9ec08f8eb484.png)

This Django middleware looks popular: https://github.com/ottoyiu/django-cors-headers

**Comment by DingoEatingFuzz** [comment]
Reading through the django-cors-headers docs a little, looks like what we want is to add this line to the Django project settings:

```py
CORS_ORIGIN_ALLOW_ALL = True
```

Oh, and add the middleware itself to the project.

**Comment by jaymcgrath** [comment]
I also added a this line: 
`CORS_URLS_REGEX = r'^housing_api/.*$'`
to only set CORS headers for the API
